print("--------------------------------------------------")
print("      *** Welcome to Band Name Generator ***")
print("--------------------------------------------------\n")
cityName = input("*  What's name of the city you grew up in?\n-> Answer:\t")
petName = input("*  What's your pet's name?\n-> Answer:\t")
print("")
print(f"Your band name could be {cityName} {petName}")
